DAW/Models/Proposals.cs
namespace ProiectDAW.Models
{
    public class Proposals  

    {
        public int ID { get; set; }

        public string Name { get; set; }
        public DateTime Date { get; set; } = DateTime.Now;

        public string ProposalBody { get; set; }

    }
}

DAW/Pages/AddExternalNewsPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProiectDAW.Models;
using ProiectDAW.ContextModels;
using Microsoft.EntityFrameworkCore;

namespace ProiectDAW.Pages
{
    public class AddExternalNewsPage : PageModel
    {
        [BindProperty]

        public News news { get; set; }
        [BindProperty]
        public Category category { get; set; }
        public List<SelectListItem> categories { get; set; }
        private readonly ILogger<AddExternalNewsPage> logger;
        private readonly NewsContext newsContext;
        private readonly IWebHostEnvironment webHostEnvironment;
        public IFormFile Image { get; set; }
        public int errorCode { get; set; }

        public AddExternalNewsPage(ILogger<AddExternalNewsPage> logger, NewsContext newsContext, IWebHostEnvironment webHostEnvironment)
        {
            this.logger = logger;
            this.newsContext = newsContext;
            this.webHostEnvironment = webHostEnvironment;
        }

        public void OnGet(int errorCode)
        {
            news = new News();
            this.errorCode=errorCode;
        }
        [HttpPost]
        public IActionResult OnPostAddExternalNews()
        {
            news.SubCategoryId = 2007;
            if (news.NewsTitle == null || news.Body == null)
                return RedirectToPage("AddExternalNewsPage", new { NewsId = news.Id, errorCode = 1 });
            string fileName = null;
            if (Image != null)
            {
                string uploadDir = Path.Combine(webHostEnvironment.WebRootPath, "Images");
                fileName = Guid.NewGuid().ToString() + "-" + Image.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Image.CopyTo(fileStream);
                }
            }
            string stringFileName = fileName;
            news.Image = stringFileName;
            newsContext.Add(news);
            newsContext.SaveChanges();
            return RedirectToPage("Index");
        }
    }
}

DAW/Pages/AddInternalNewsPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProiectDAW.Models;
using ProiectDAW.ContextModels;
using Microsoft.EntityFrameworkCore;

namespace ProiectDAW.Pages
{
    public class AddInternalNewsPage : PageModel
    {
        [BindProperty]

        public News news { get; set; }
        [BindProperty]
        public Category category { get; set; }
        [BindProperty]
        public SubCategory subCategory { get; set; }
        public List<SelectListItem> subcategories { get; set; }
        public List<SelectListItem> categories { get; set; }
        private readonly ILogger<AddInternalNewsPage> logger;
        private readonly NewsContext newsContext;
        private readonly IWebHostEnvironment webHostEnvironment;
        public int errorCode { get; set; }
        public IFormFile Image { get; set; }

        public AddInternalNewsPage(ILogger<AddInternalNewsPage> logger, NewsContext newsContext, IWebHostEnvironment webHostEnvironment)
        {
            this.logger = logger;
            this.newsContext = newsContext;
            this.webHostEnvironment = webHostEnvironment;
        }

        public void OnGet(int errorCode)
        {
            news = new News();
            subcategories = newsContext.SubCategories.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.SubCategoryName
            }).ToList();

            categories = newsContext.Categories.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.CategoryName
            }).ToList();
            this.errorCode = errorCode;
        }
        [HttpPost]
        public IActionResult OnPostAddInternalNews()
        {
            if (news.Writer == null || news.NewsTitle == null || news.Lead == null || news.Body == null)
                return RedirectToPage("AddInternalNewsPage", new { NewsId = news.Id, errorCode = 1 });
            string fileName = null;
            if(Image != null)
            {
                string uploadDir = Path.Combine(webHostEnvironment.WebRootPath, "Images");
                fileName = Guid.NewGuid().ToString() + "-" + Image.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Image.CopyTo(fileStream);
                }
            }
            string stringFileName = fileName;
            news.Image = stringFileName;
            newsContext.Add(news);
            newsContext.SaveChanges();
            return RedirectToPage("Index");
        }

        public IActionResult OnPostAddCategory()
        {
            if (category.CategoryName == null)
                return RedirectToPage("AddNewsPage", new { NewsId = news.Id, errorCode = 1 });
            newsContext.Add(category);
            newsContext.SaveChanges();
            return RedirectToPage("AddNewsPage", new { NewsId = news.Id, errorCode = 0 });
        }

        public IActionResult OnPostAddSubCategory()
        {
            if (subCategory.SubCategoryName == null)
                return RedirectToPage("AddNewsPage", new { NewsId = news.Id, errorCode = 1 });
            newsContext.Add(category);
            newsContext.SaveChanges();
            return RedirectToPage("AddNewsPage", new { NewsId = news.Id, errorCode = 0 });
        }

    }
}

DAW/Pages/AddNewsPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProiectDAW.Models;
using ProiectDAW.ContextModels;
using Microsoft.EntityFrameworkCore;

namespace ProiectDAW.Pages
{
    public class AddNewsPage : PageModel
    {
        public List<SelectListItem> subcategories { get; set; }
        private readonly ILogger<AddNewsPage> logger;
        private readonly NewsContext newsContext;

        public AddNewsPage(ILogger<AddNewsPage> logger, NewsContext newsContext)
        {
            this.logger = logger;
            this.newsContext = newsContext;
        }

        public IActionResult OnPost()
        {
            return RedirectToPage("AddInternalNewsPage");
        }
    }
}

DAW/Pages/DeleteNewsPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProiectDAW.Models;
using ProiectDAW.ContextModels;
using Microsoft.EntityFrameworkCore;

namespace ProiectDAW.Pages
{
    public class DeleteNewsPage : PageModel
    {
        public static News News { get; set; }
        private readonly ILogger<DeleteNewsPage> logger;
        private readonly NewsContext newsContext;
        public List<Comments> Comments { get; set; }   

        public DeleteNewsPage(ILogger<DeleteNewsPage> logger, NewsContext newsContext)
        {
            this.logger = logger;
            this.newsContext = newsContext;
        }

        public void OnGet(int NewsId)
        {
            Comments = newsContext.Comments.Where(x => x.NewsId == NewsId).ToList();
            News=newsContext.News.Include(news=>news.SubCategory).FirstOrDefault(x=>x.Id==NewsId);
        }

        public IActionResult OnPost()
        {
            if(News!=null)
            {
                newsContext.Remove(News);
                newsContext.SaveChanges();
            }
            if(Comments!=null)
            {
                newsContext.Remove(Comments);
                newsContext.SaveChanges();
            }
            return RedirectToPage("Index");
        }
    }
}

DAW/Pages/EditNewsPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProiectDAW.Models;
using ProiectDAW.ContextModels;
using Microsoft.EntityFrameworkCore;
using ProiectDAW.Pages;

namespace ProiectDAW.Pages
{
    public class EditNewsPageModel : PageModel
    {
        [BindProperty]
        public News news { get; set; }
        public List<SelectListItem> subcategories { get; set; }
        private readonly ILogger<EditNewsPageModel> logger;
        private readonly NewsContext newsContext;
        public int errorCode { get; set; }

        public EditNewsPageModel(ILogger<EditNewsPageModel> logger, NewsContext newsContext)
        {
            this.logger = logger;
            this.newsContext = newsContext;
        }

        public void OnGet(int NewsId, int errorCode)
        {
            news = newsContext.News.Include(news => news.SubCategory.Category).FirstOrDefault( x=> x.Id == NewsId);
            subcategories = newsContext.SubCategories.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.SubCategoryName
            }).ToList();
            this.errorCode = errorCode;
        }

        public IActionResult OnPost()
        {
            if (news.NewsTitle == null || news.Lead == null || news.Body == null)
                return RedirectToPage("EditNewsPage", new { errorCode = 1 });
            newsContext.Update(news);
            newsContext.SaveChanges();
            return RedirectToPage("Index");
        }
    }
}

DAW/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ProiectDAW.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

DAW/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProiectDAW.Models;
using ProiectDAW.ContextModels;
using Microsoft.EntityFrameworkCore;

namespace ProiectDAW.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> logger;
        private readonly NewsContext newsContext;

        public List<News> News { get; set; }
        static public List<Category> Categories { get; set; }

        public IndexModel(ILogger<IndexModel> logger, NewsContext newsContext)
        {
            this.logger = logger;
            this.newsContext = newsContext;
        }

        public void OnGet()
        {
            News = this.newsContext.News.Include(news => news.SubCategory.Category).ToList();
            News = News.OrderByDescending(news => news.Date).ToList();
            Categories = this.newsContext.Categories.ToList();
            Categories = Categories.OrderByDescending(Categories => Categories.CategoryName).ToList();
        }
        [HttpPost]
        public IActionResult OnPost()
        {
            String title = Request.Form["searchText"];
            var AllNews = newsContext.News.Include(news => news.SubCategory.Category).ToList();
            News = AllNews.Where(news => news.NewsTitle.Contains(title) || title==null).ToList();
            News = News.OrderByDescending(news => news.Date).ToList();

            return Page();
        }
    }
}

DAW/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProiectDAW.Models;
using ProiectDAW.ContextModels;
using Microsoft.EntityFrameworkCore;


namespace ProiectDAW.Pages
{
    public class LoginModel : PageModel
    {
        public int errorCode { get; set; }
        public bool IsLoggedIn { get; set; }
        [BindProperty]
        public Accounts Account { get; set; }

        private readonly ILogger<LoginModel> logger;

        private readonly NewsContext newsContext;
        public LoginModel(ILogger<LoginModel> logger, NewsContext newsContext)
        {
            this.logger = logger;
            this.newsContext = newsContext;
        }
        public void OnGet(int errorCode)
        {
            this.errorCode = errorCode;
            Account = new Accounts();
        }
        public IActionResult OnPost()
        {
            LoggingSystem loggingSystem = LoggingSystem.GetInstance();
            Accounts account = loggingSystem.LogIn(Account, newsContext.Accounts.Include(type => type.Type).ToList());
            if (account != null)
            {
                loggingSystem.Account = account;
                return RedirectToPage("Index");
            }

            return RedirectToPage("Login", new { errorCode = 1 });
        }

    }
}

DAW/Pages/NewsPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProiectDAW.Models;
using ProiectDAW.ContextModels;
using Microsoft.EntityFrameworkCore;

namespace ProiectDAW.Pages
{
    public class NewsPageModel : PageModel
    {
        
        public News News { get; set; }
        [BindProperty]
        public Comments comm { get; set; }
        private readonly ILogger<NewsPageModel> logger;
        private readonly NewsContext newsContext;
        public List<Comments> Comments { get; set; }   
        public string page { get; set; }

        public NewsPageModel(ILogger<NewsPageModel> logger, NewsContext newsContext)
        {
            this.logger = logger;
            this.newsContext = newsContext;
        }

        public void OnGet(int NewsId)
        {
            comm = new Comments();
            comm.NewsId=NewsId;
            Comments = newsContext.Comments.Where(x => x.NewsId == NewsId).ToList();
            News=newsContext.News.Include(news=>news.SubCategory).FirstOrDefault(x=>x.Id==NewsId);
            page = "NewsPage" + "/" + News.Id.ToString();

        }
        public IActionResult OnPost()
        {
            newsContext.Add(comm);
            newsContext.SaveChanges();
            return RedirectToPage(page);
        }
    }
}

DAW/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProiectDAW.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

DAW/Pages/Proposal.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProiectDAW.Models;
using ProiectDAW.ContextModels;
using Microsoft.EntityFrameworkCore;

namespace ProiectDAW.Pages
{
    public class ProposalModel : PageModel
    {
        private readonly ILogger<ProposalModel> logger;
        private readonly NewsContext newsContext;
        public List<Proposals> Prop { get; set; }
        [BindProperty]
        public Proposals proposal { get; set; } 

        public ProposalModel(ILogger<ProposalModel> logger, NewsContext newsContext)
        {
            this.logger = logger;
            this.newsContext = newsContext;
        }

        public void OnGet()
        {
            Prop = this.newsContext.Proposals.ToList();
            Prop=Prop.OrderByDescending(x=>x.Date).ToList();
        }

        public IActionResult OnPost(String searchText)
        {
            newsContext.Add(proposal);
            newsContext.SaveChanges();
            return RedirectToPage("/Proposal");
        }
    }
}

DAW/Pages/UserRights.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProiectDAW.Models;
using ProiectDAW.ContextModels;
using Microsoft.EntityFrameworkCore;

namespace ProiectDAW.Pages
{
    public class UserRightsModel : PageModel
    {
        public static int userId = 1;
        public static int editorId = 2;

        [BindProperty]
        public Accounts account { get; set; }
        public List<Accounts> accounts { get; set; }
        public List<AccountTypes> accountTypes { get; set; }

        private readonly ILogger<UserRightsModel> logger;
        private readonly NewsContext newsContext;

        public UserRightsModel(ILogger<UserRightsModel> logger, NewsContext newsContext)
        {
            this.logger = logger;
            this.newsContext = newsContext;
            accountTypes = newsContext.AccountTypes.ToList();
        }
        public void OnGet()
        {
            accounts = this.newsContext.Accounts.Include(account => account.Type).ToList();
            accounts = accounts.OrderByDescending(account => account.Username).ToList();
        }

        public IActionResult OnPostRemove()
        {
            account.TypeId = userId;
            newsContext.Update(account);
            newsContext.SaveChanges();
            return RedirectToPage("UserRights");
        }

        public IActionResult OnPostAdd()
        {
            account.TypeId = editorId;
            newsContext.Update(account);
            newsContext.SaveChanges();
            return RedirectToPage("UserRights");
        }

    }
}

DAW/Pages/AddExternalNewsPage.cshtml
@page "{errorCode:int}"
@model AddExternalNewsPage
@{
}

<div>
     @if (Model.errorCode == 1)
    {
        <div>
            <p>Fields can not be empty!</p>
        </div>
    }

    <h1>Add your news below:</h1>

    <form method="post" id="form-external" enctype="multipart/form-data" asp-page-handler="AddExternalNews" >
        <label>Title: </label>
        <input asp-for="news.NewsTitle" /> <br></br>

        <label>Lead: </label>
        <input asp-for="news.Lead" /><br></br>

        <label>The body: </label><br />
        <textarea asp-for="news.Body" form="form-external" placeholder="Link of the news..."></textarea><br></br>

        <label>Refference Link: </label>
        <input asp-for="news.RefferenceLink" /><br></br>


        </select>
        <br></br>
        <label>Date: </label>
        <input asp-for="news.Date" /><br></br>
            <div class="form-control">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
        <input type="submit" value="Submit" />
        <button><a asp-page="\Index">Cancel </a></button>
    </form>
</div>

DAW/Pages/AddInternalNewsPage.cshtml
@page "{errorCode:int}"
@model AddInternalNewsPage
@{
}

<div>
    @if (Model.errorCode == 1)
    {
        <div>
            <p>Fields can not be empty!</p>
        </div>
    }

    <h1>Add your news below:</h1>

    <form method="post" id="form-internal" enctype="multipart/form-data" asp-page-handler="AddInternalNews" >
        <label>Title: </label>
        <input asp-for="news.NewsTitle" /> <br></br>

        <label>Lead: </label>
        <input asp-for="news.Lead" /><br></br>

        <label>Writer: </label>
        <input asp-for="news.Writer" /><br></br>

        <label>The body: </label><br />
        <textarea asp-for="news.Body" form="form-internal" placeholder="The story..."></textarea><br></br>

        <label>Subcategory: </label>
        <select asp-for="news.SubCategoryId" asp-items="Model.subcategories">
            
        </select>
        <br></br>
        <label>Date: </label>
        <input asp-for="news.Date" /><br></br>
            <div class="form-control">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
        <input type="submit" value="Submit" />
        <button><a asp-page="\Index">Cancel </a></button>

    </form>

        <h1>Add a new category:</h1>

    <form method="post" asp-page-handler="AddCategory">
        <label>Subcategory name: </label>
        <input asp-for="category.CategoryName" /> <br></br>

        <input type="submit" value="Submit" />

    </form>

    <h1>Add a new subcategory:</h1>

    <form method="post" asp-page-handler="AddSubCategory">
        <label>Category name: </label>
        <input asp-for="subCategory.SubCategoryName" /> <br></br>

        <label>Category: </label>
        <select asp-for="subCategory.CategoryId" asp-items="Model.categories">

        </select><br></br>

        <input type="submit" value="Submit" />


    </form>
</div>

DAW/Pages/AddNewsPage.cshtml
@page 
@model AddNewsPage
@{
}

    <h2>Would you like to add your own news or would you like to share a news from a different place?</h2>
<div class="container-test" style="display: flex; justify-content: space-between;">
    <div style="height: 500px;">
        <p>If you would like to add your own news select below:</p>
        <button><a asp-route-errorCode="0" asp-page="\AddInternalNewsPage">Go! </a></button>
    </div>
    <div style="height: 500px;">
                <p>If you would like to add your own news select below:</p>
        <button><a asp-route-errorCode="0" asp-page="\AddExternalNewsPage">Go! </a></button>
    </div>
</div>

DAW/Pages/DeleteNewsPage.cshtml
@page "{NewsId:int}"
@model DeleteNewsPage
@{
}

<div>
    <form method="post">
        <label>Are you sure you want to delete this news?</label>
        <br>
        <input type="submit" value="Submit" />
        <button><a asp-page="\Index">Cancel </a></button>
    </form>
</div>

DAW/Pages/EditNewsPage.cshtml
@page "{NewsId:int}/{errorCode:int}"
@using ProiectDAW.Models
@model ProiectDAW.Pages.EditNewsPageModel
@{
}

<div>

    @if (Model.errorCode == 1)
    {
        <div>
            <p>Fields can not be empty!</p>
        </div>
    }

    <h1>Edit your news below:</h1>

    <form method="post" id="form-body2">
        <input asp-for="news.Id" type="hidden" /> <br></br>
        <label>Title: </label>
        <input asp-for="news.NewsTitle" /> <br></br>

        <label>Lead: </label>
        <input asp-for="news.Lead" /><br></br>

        <label>Writer: </label>
        <input asp-for="news.Writer" /><br></br>

        <label>The body: </label><br />
        <textarea asp-for="news.Body" form="form-body2" placeholder="Comentariul tau..."></textarea>
        <br></br>

        <label>Subcategory: </label>
        <select asp-for="news.SubCategoryId" asp-items="Model.subcategories">
            
        </select>
        <br></br>
        <label>Date: </label>
        <input asp-for="news.Date" /><br></br>

        <input type="submit" value="Submit" />
        <button><a asp-page="\Index">Cancel </a></button>

    </form>
</div>

DAW/Pages/Login.cshtml
@page "{errorCode:int}"
@model ProiectDAW.Pages.LoginModel
@{
}

<div class="container-login">
	<div class="screen">
		<div class="screen__content">
			@if (Model.errorCode == 1)
			{
				<div class="alert">
					<p>Wrong credentials!</p>
				</div>
			}
			<form class="login" method="post">
				<div class="login__field">
					<i class="login__icon fas fa-user"></i>
					<input asp-for="Account.Username" type="text" class="login__input" placeholder="User name / Email">
				</div>
				<div class="login__field">
					<i class="login__icon fas fa-lock"></i>
					<input asp-for="Account.Password" type="password" class="login__input" placeholder="Password">
				</div>
				<button class="button login__submit">
					<span class="button__text">Log In Now</span>
					<i class="button__icon fas fa-chevron-right"></i>
					<input type="submit" value="Login" />
				</button>
			</form>
		</div>
		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>
	</div>
</div>

DAW/Pages/Proposal.cshtml
@page
@model ProiectDAW.Pages.ProposalModel
@{
    ViewData["Title"] = "Home page";
}

<div class="proposal-wrapper">
    

        <div class="container-form">
            <h1 class="form__title">
                Your Proposal
            </h1>
            <div class="screen">
                <div class="screen__content">
                    <form class="form" id="form-proposal" method="post">
                        <div class="form__field">
                            <i class="form__icon fas fa-user"></i>
                            <input asp-for="proposal.Name" type="text" class="form__input" placeholder="Name">
                        </div>
                        <div class="form__field">
                            <i class="form__icon fas fa-lock"></i>
                            <textarea asp-for="proposal.ProposalBody" rows="2" form="form-proposal" placeholder="The topic of choice..."></textarea><br></br>

                        </div>
                        <input type="submit" value="Save" class="button form__submit" />
                    </form>
                </div>
                <div class="screen__background">
                    <span class="screen__background__shape screen__background__shape4"></span>
                    <span class="screen__background__shape screen__background__shape3"></span>
                    <span class="screen__background__shape screen__background__shape2"></span>
                    <span class="screen__background__shape screen__background__shape1"></span>
                </div>
            </div>
        </div>



        <div class="container-proposal">
            <div class="row justify-content-center" style="width: 100%;">
                <div class="col-md-8">
                    <div class="page-header">
                        <h1 style="border-bottom: 1px solid gray;"><small class="pull-right">@Model.Prop.Count proposals</small></h1>
                    </div>
                    <div class="media">
                        <div class="media-body">
                            @foreach (Models.Proposals prop in @Model.Prop)
                            {
                                <h4 class="media-heading user_name"> @prop.Name proposed: </h4>
                                <p>@prop.ProposalBody</p>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>

DAW/Pages/UserRights.cshtml
@page
@using ProiectDAW.Models
@model UserRightsModel
@{
}

<div class="catalog">
    @foreach (Models.Accounts account in Model.accounts)
    {

        @if (account.TypeId == Pages.UserRightsModel.userId)
        {
            <p>Username: @account.Username</p>

            @foreach (Models.AccountTypes accountType in Model.accountTypes)
            {
                @if (@accountType.Id == @account.TypeId)
                {
                    <label> Role: @accountType.Type </label>
                }
            }

            <form method="post" asp-page-handler="Add">
            <input asp-for="@account.Id" type="hidden" />

            <input asp-for="@account.Password" type="hidden" />

            <input asp-for="@account.Username" type="hidden" />

            <input type="submit" value="Make editor" />
            </form>
        } else if (account.TypeId == Pages.UserRightsModel.editorId)
        {
            <p>Username: @account.Username</p>

            @foreach (Models.AccountTypes accountType in Model.accountTypes)
            {
                @if (@accountType.Id == @account.TypeId)
                {
                    <label> Role: @accountType.Type </label>
                }
            }

            <form method="post" asp-page-handler="Remove">
                <input asp-for="@account.Id" type="hidden" />

                <input asp-for="@account.Password" type="hidden" />

                <input asp-for="@account.Username" type="hidden" />

                <input type="submit" value="Remove editor rights" />
            </form>
        }

         
    }
</div>